apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio 
    spec:
      containers:
      - name: nodeserver
        image: muhammadalfarizit/portfolio:latest
        ports:
        - containerPort: 3000